package standalone.prng;

/**
 * Stream based Cryptographic Pseudo Random number Interface
 * Outputs are of OutLength of underlying Hash
 */
public interface Prng {
    //get the indes of the current random number(how many numbers where already generated by this)
    public long index();
    //get the current random number
    public byte[] current();
    //trans form state to provide a new random number
    public void next();
    //make a copy of this, which stores the state and envolves seperately
    public Prng capture();
}
