package suit.algorithms.interfaces;


import suit.tools.arrays.DataArray;
import test.measure.SpaceMeasureable;

/**
 * Basic Merkle Tree interface for generating AuthPaths
 * (Shared between IMerkle Tree and ISignatureTree)
 */
public interface ITree extends SpaceMeasureable {
     //inits the merkle tree (this can depending on H take a long time)
     public void init();
     //make a single intit step (mainly for debugging and time measurement)
     public boolean initStep();
     //checks if more Auth paths gan be generated by this Tree
     public boolean canAuthMore();
     //Gets the root of this tree
     public DataArray getRootPk();
     //do an update (allows out of order update in between auth path genaration to reduce respond times)
     public void updateStep();
}
