package suit.algorithms.interfaces;


import suit.tools.arrays.DataArray;
import test.measure.SpaceMeasureable;

/**
 * Stream based Cryptographic Pseudo Random number Interface
 * Outputs are of OutLength of underlying Hash
 */
public interface ICryptPrng extends SpaceMeasureable{
    //get the indes of the current random number(how many numbers where already generated by this)
    public long index();
    //get the current random number
    public DataArray current();
    //trans form state to provide a new random number
    public void next();
    //make a copy of this, which stores the state and envolve sepoerately
    public ICryptPrng capture();
}
